# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approximate_pseudo_octave <- function(unsorted_x, uncertainty) {
    .Call(`_mami_codi_beaty_R_approximate_pseudo_octave`, unsorted_x, uncertainty)
}

rational_fractions <- function(x, x_ref, uncertainty) {
    .Call(`_mami_codi_beaty_R_rational_fractions`, x, x_ref, uncertainty)
}

approximate_rational_fractions <- function(x, x_ref, uncertainty) {
    .Call(`_mami_codi_beaty_R_approximate_rational_fractions`, x, x_ref, uncertainty)
}

compute_cubic_distortion_products <- function(frequency, amplitude, alpha = 1.0) {
    .Call(`_mami_codi_beaty_R_compute_cubic_distortion_products`, frequency, amplitude, alpha)
}

