# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rational_fractions <- function(x, x_ref, uncertainty) {
    .Call(`_mami_codi_beaty_R_rational_fractions`, x, x_ref, uncertainty)
}

approximate_pseudo_octave <- function(harmonic_ratio, uncertainty) {
    .Call(`_mami_codi_beaty_R_approximate_pseudo_octave`, harmonic_ratio, uncertainty)
}

approximate_rational_fractions <- function(x, x_ref, uncertainty) {
    .Call(`_mami_codi_beaty_R_approximate_rational_fractions`, x, x_ref, uncertainty)
}

compute_cubic_distortion_products <- function(frequency, amplitude) {
    .Call(`_mami_codi_beaty_R_compute_cubic_distortion_products`, frequency, amplitude)
}

