# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approximate_pseudo_octave <- function(ratios, uncertainty) {
    .Call(`_mami_codi_beaty_R_approximate_pseudo_octave`, ratios, uncertainty)
}

approximate_rational_fractions <- function(x, uncertainty) {
    .Call(`_mami_codi_beaty_R_approximate_rational_fractions`, x, uncertainty)
}

compute_amplitude_modulation <- function(frequency, amplitude) {
    .Call(`_mami_codi_beaty_R_compute_amplitude_modulation`, frequency, amplitude)
}

